service: serverless-infra

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}

functions:
  - ${file(src/serverless-app-1/serverless.yml)}
  - ${file(src/serverless-app-2/serverless.yml)}
