name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - run: "echo hi"
      # - run: |
      #     curl -X POST https://api.github.com/repos/:owner/:repo/dispatches \
      #     -H 'Accept: application/vnd.github.everest-preview+json' \
      #     -u $your_user:$your_personal_access_token \